In [1]:
import pandas as pd
from statsbombpy import sb
import numpy as np

pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.max_rows", None)  # Show all rows
#pd.set_option("display.max_colwidth", None)  # Don't truncate text in cells
#pd.set_option("display.width", None)  # Don't wrap output

In [2]:
competitions = sb.competitions()
competitions.head()

/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,None,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

In [ ]:
top_leagues = [
    "1. Bundesliga",
    #"African Cup of Nations",
    "Champions League",
    #"Copa America",
    #"FIFA World Cup",
    "La Liga",
    "Ligue 1",
    "Premier League",
    "Serie A",
    #"UEFA Euro",
    #"UEFA Europa League",
]

In [4]:
competitions[competitions['competition_name'].isin(top_leagues)].head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,None,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

In [5]:
matches = sb.matches(competition_id=9, season_id=27)
matches.head()

/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,competition_id,competition_country_name,competition_name,competition,season_id,season,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3890563,2016-05-14,15:30:00.000,3,2,available,unscheduled,2023-08-05T09:38:01.494282,None,34,9,Germany,1. Bundesliga,Germany - 1. Bundesliga,27,2015/2016,904,Bayer Leverkusen,male,None,85,Germany,189,Ingolstadt,male,None,85,Germany,1,Regular Season,377,BayArena,85,Germany,227,Guido Winkmann,85,Germany,Roger Schmidt,Ralph Hasenhüttl,3980,Roger Schmidt,None,1967-03-13,85,Germany,44,Ralph Hasenhüttl,None,1967-08-09,15,Austria,1.1.0,2,2
1,3890550,2016-05-07,15:30:00.000,2,1,available,unscheduled,2023-10-28T23:30:33.200742,None,33,9,Germany,1. Bundesliga,Germany - 1. Bundesliga,27,2015/2016,185,Borussia Mönchengladbach,male,None,85,Germany,904,Bayer Leverkusen,male,None,85,Germany,1,Regular Season,372,Stadion im BORUSSIA-PARK,85,Germany,245,Bastian Dankert,85,Germany,André Schubert,Roger Schmidt,3650,André Schubert,None,1971-07-24,85,Germany,3980,Roger Schmidt,None,1967-03-13,85,Germany,1.1.0,2,2
2,3890540,2016-04-30,18:30:00.000,2,1,available,unscheduled,2023-07-24T07:41:44.627113,None,32,9,Germany,1. Bundesliga,Germany - 1. Bundesliga,27,2015/2016,904,Bayer Leverkusen,male,None,85,Germany,173,Hertha Berlin,male,None,85,Germany,1,Regular Season,377,BayArena,85,Germany,229,Tobias Stieler,85,Germany,Roger Schmidt,Pál Dárdai,3980,Roger Schmidt,None,1967-03-13,85,Germany,51,Pál Dárdai,None,1976-03-16,103,Hungary,1.1.0,2,2
3,3890534,2016-04-23,18:30:00.000,2,3,available,unscheduled,2023-07-19T17:07:48.502966,None,31,9,Germany,1. Bundesliga,Germany - 1. Bundesliga,27,2015/2016,181,Schalke 04,male,None,85,Germany,904,Bayer Leverkusen,male,None,85,Germany,1,Regular Season,370,VELTINS-Arena,85,Germany,716,Wolfgang Stark,85,Germany,André Breitenreiter,Roger Schmidt,58,André Breitenreiter,None,1973-10-02,85,Germany,3980,Roger Schmidt,None,1967-03-13,85,Germany,1.1.0,2,2
4,3890521,2016-04-16,15:30:00.000,3,0,available,unscheduled,2023-07-25T09:12:32.507875,None,30,9,Germany,1. Bundesliga,Germany - 1. Bundesliga,27,2015/2016,904,Bayer Leverkusen,male,None,85,Germany,184,Eintracht Frankfurt,male,None,85,Germany,1,Regular Season,377,BayArena,85,Germany,231,Deniz Aytekin,85,Germany,Roger Schmidt,Niko Kovač,3980,Roger Schmidt,None,1967-03-13,85,Germany,374,Niko Kovač,None,1971-10-15,56,Croatia,1.1.0,2,2

In [6]:
events = sb.events(match_id=3890550)
events = events.sort_values('index')

/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [7]:
pd.set_option("display.max_columns", None)

events.head(10)

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_no_touch,dribble_nutmeg,dribble_outcome,dribble_overrun,duel_outcome,duel_type,duration,foul_committed_advantage,foul_committed_card,foul_committed_offensive,foul_committed_type,foul_won_advantage,foul_won_defensive,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_outcome,goalkeeper_position,goalkeeper_shot_saved_to_post,goalkeeper_technique,goalkeeper_type,id,index,interception_outcome,location,match_id,minute,off_camera,out,pass_aerial_won,pass_angle,pass_assisted_shot_id,pass_body_part,pass_cross,pass_cut_back,pass_deflected,pass_end_location,pass_goal_assist,pass_height,pass_inswinging,pass_length,pass_outcome,pass_outswinging,pass_recipient,pass_recipient_id,pass_shot_assist,pass_switch,pass_technique,pass_through_ball,pass_type,period,play_pattern,player,player_id,position,possession,possession_team,possession_team_id,related_events,second,shot_aerial_won,shot_body_part,shot_deflected,shot_end_location,shot_first_time,shot_freeze_frame,shot_key_pass_id,shot_one_on_one,shot_outcome,shot_saved_to_post,shot_statsbomb_xg,shot_technique,shot_type,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,872b1174-31fc-4bd1-b77a-031ad6fc5eef,1,NaN,NaN,3890550,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Borussia Mönchengladbach,185,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'formation': 3412, 'lineup': [{'player': {'id...",Borussia Mönchengladbach,185,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b4679dd8-c2e4-49e2-b1ba-4132255c72d9,2,NaN,NaN,3890550,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Borussia Mönchengladbach,185,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'formation': 442, 'lineup': [{'player': {'id'...",Bayer Leverkusen,904,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b7634bbf-f73d-4114-81ab-710f6a423273,3,NaN,NaN,3890550,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Borussia Mönchengladbach,185,[b8c7457e-6921-4760-9cfd-b5ed5a7687f6],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b8c7457e-6921-4760-9cfd-b5ed5a7687f6,4,NaN,NaN,3890550,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Borussia Mönchengladbach,185,[b7634bbf-f73d-4114-81ab-710f6a423273],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borussia Mönchengladbach,185,00:00:00.000,Half Start,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.455590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53aade16-5698-47e7-8e14-ac97a84a8f8c,5,NaN,"[60.0, 40.0]",3890550,0,NaN,NaN,NaN,0.361729,NaN,Right Foot,NaN,NaN,NaN,"[63.7, 41.4]",NaN,Ground Pass,NaN,3.956008,NaN,NaN,Lars Edi Stindl,8806.0,NaN,NaN,NaN,NaN,Kick Off,1,From Kick Off,Raffael Caetano de Araújo,8810.0,Left Center Forward,2,Borussia Mönchengladbach,185,[e13888d8-cc59-4927-96b6-6807026a4de9],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borussia Mönchengladbach,185,00:00:00.459,Pass,NaN
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e13888d8-cc59-4927-96b6-6807026a4de9,6,NaN,"[63.7, 41.4]",3890550,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,From Kick Off,Lars Edi Stindl,8806.0,Center Attacking Midfield,2,Borussia Mönchengladbach,185,[53aade16-5698-47e7-8e14-ac97a84a8f8c],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borussia Mönchengladbach,185,00:00:00.914,Ball Receipt*,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.357556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ddc25ef4-52ec-4ad3-83d9-da2c19d6108b,7,NaN,"[63.9, 41.8]",3890550,0,NaN,NaN,NaN,-2.716493,NaN,Right Foot,NaN,NaN,NaN,"[34.3, 28.4]",NaN,Ground Pass,NaN,32.491844,NaN,NaN,Håvard Nordtveit,8395.0,NaN,NaN,NaN,NaN,NaN,1,From Kick Off,Lars Edi Stindl,8806.0,Center Attacking Midfield,2,Borussia Mönchengladbach,185,[5e9d4915-6bb1-4e0f-ab44-82556a7cb1df],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borussia Mönchengladbach,185,00:00:00.914,Pass,NaN
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5e9d4915-6bb1-4e0f-ab44-82556a7cb1df,8,NaN,"[34.3, 28.4]",3890550,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,From Kick Off,Håvard Nordtveit,8395.0,Left Center Back,2,Borussia Mönchengladbach,185,[ddc25ef4-52ec-4ad3-83d9-da2c19d6108b],2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borussia Mönchengladbach,185,00:00:02.272,Ball Receipt*,NaN
1939,NaN,NaN,NaN,NaN,NaN,"[34.3, 28.4]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.455590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,085eac04-f567-4c1a-bacc-46161e4481d1,9,NaN,"[34.3, 28.4]",3890550,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,From Kick Off,Håvard Nordtveit,8395.0,Left Center Back,2,Borussia Mönchengladbach,185,"[5e9d4915-6bb1-4e0f-ab44-82556a7cb1df, 9691a4e...",2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borussia Mönchengladbach,185,00:00:02.272,Carry,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.741941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9691a4ec-fd94-4eee-b338-2dc144cf3d04,10,NaN,"[34.3, 28.4]",3890550,0,NaN,NaN,NaN,0.509758,NaN,Right Foot,NaN,NaN,NaN,"[88.5, 58.7]",NaN,High Pass,NaN,62.094524,Incomplete,NaN,André Hahn,8322.0,NaN,NaN,NaN,NaN,NaN,1,From Kick Off,Håvard Nordtveit,8395.0,Left Center Back,2,Borussia Mönchengladbach,185,"[3b86b372-fcd4-4452-b6a2-1234554bf64c, a6d4abe...",3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borussia Mönchengladbach,185,00:00:03.727,Pass,NaN

In [8]:
events.columns

Index(['50_50', 'ball_receipt_outcome', 'ball_recovery_recovery_failure',
       'block_deflection', 'block_offensive', 'carry_end_location',
       'clearance_aerial_won', 'clearance_body_part', 'clearance_head',
       'clearance_left_foot', 'clearance_right_foot', 'counterpress',
       'dribble_no_touch', 'dribble_nutmeg', 'dribble_outcome',
       'dribble_overrun', 'duel_outcome', 'duel_type', 'duration',
       'foul_committed_advantage', 'foul_committed_card',
       'foul_committed_offensive', 'foul_committed_type', 'foul_won_advantage',
       'foul_won_defensive', 'goalkeeper_body_part', 'goalkeeper_end_location',
       'goalkeeper_outcome', 'goalkeeper_position',
       'goalkeeper_shot_saved_to_post', 'goalkeeper_technique',
       'goalkeeper_type', 'id', 'index', 'interception_outcome', 'location',
       'match_id', 'minute', 'off_camera', 'out', 'pass_aerial_won',
       'pass_angle', 'pass_assisted_shot_id', 'pass_body_part', 'pass_cross',
       'pass_cut_back', 'pass_deflected', 'pass_end_location',
       'pass_goal_assist', 'pass_height', 'pass_inswinging', 'pass_length',
       'pass_outcome', 'pass_outswinging', 'pass_recipient',
       'pass_recipient_id', 'pass_shot_assist', 'pass_switch',
       'pass_technique', 'pass_through_ball', 'pass_type', 'period',
       'play_pattern', 'player', 'player_id', 'position', 'possession',
       'possession_team', 'possession_team_id', 'related_events', 'second',
       'shot_aerial_won', 'shot_body_part', 'shot_deflected',
       'shot_end_location', 'shot_first_time', 'shot_freeze_frame',
       'shot_key_pass_id', 'shot_one_on_one', 'shot_outcome',
       'shot_saved_to_post', 'shot_statsbomb_xg', 'shot_technique',
       'shot_type', 'substitution_outcome', 'substitution_outcome_id',
       'substitution_replacement', 'substitution_replacement_id', 'tactics',
       'team', 'team_id', 'timestamp', 'type', 'under_pressure'],
      dtype='object')

In [9]:
events['type'].unique()

array(['Starting XI', 'Half Start', 'Pass', 'Ball Receipt*', 'Carry',
       'Duel', 'Clearance', 'Pressure', 'Miscontrol', 'Dispossessed',
       'Block', 'Dribbled Past', 'Dribble', 'Shot', 'Goal Keeper',
       'Ball Recovery', 'Interception', 'Foul Committed', 'Foul Won',
       '50/50', 'Injury Stoppage', 'Half End', 'Substitution',
       'Tactical Shift', 'Player Off', 'Player On'], dtype=object)

In [10]:
events[(events["type"] == "Foul Committed") & (events["foul_committed_card"] == 'Yellow Card')]

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_no_touch,dribble_nutmeg,dribble_outcome,dribble_overrun,duel_outcome,duel_type,duration,foul_committed_advantage,foul_committed_card,foul_committed_offensive,foul_committed_type,foul_won_advantage,foul_won_defensive,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_outcome,goalkeeper_position,goalkeeper_shot_saved_to_post,goalkeeper_technique,goalkeeper_type,id,index,interception_outcome,location,match_id,minute,off_camera,out,pass_aerial_won,pass_angle,pass_assisted_shot_id,pass_body_part,pass_cross,pass_cut_back,pass_deflected,pass_end_location,pass_goal_assist,pass_height,pass_inswinging,pass_length,pass_outcome,pass_outswinging,pass_recipient,pass_recipient_id,pass_shot_assist,pass_switch,pass_technique,pass_through_ball,pass_type,period,play_pattern,player,player_id,position,possession,possession_team,possession_team_id,related_events,second,shot_aerial_won,shot_body_part,shot_deflected,shot_end_location,shot_first_time,shot_freeze_frame,shot_key_pass_id,shot_one_on_one,shot_outcome,shot_saved_to_post,shot_statsbomb_xg,shot_technique,shot_type,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
3476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Yellow Card,NaN,Handball,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ee9601e4-bfb7-488b-8edd-e34372df900f,1251,NaN,"[23.1, 59.7]",3890550,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,From Free Kick,Lars Bender,8969.0,Right Back,64,Borussia Mönchengladbach,185,NaN,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:29:23.873,Foul Committed,NaN
3484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Yellow Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72cec901-9a43-4adc-b276-833f9a330077,2540,NaN,"[85.0, 15.5]",3890550,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Keeper,Oscar Wendt,8809.0,Left Wing Back,133,Borussia Mönchengladbach,185,[586a4b68-a8ce-4156-980c-24c650a707bb],19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borussia Mönchengladbach,185,00:14:19.359,Foul Committed,NaN
3489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Yellow Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2aa76c69-646b-43f2-a583-2d130aaf22aa,3036,NaN,"[21.4, 68.5]",3890550,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,Regular Play,Ibrahima Traoré,11285.0,Right Wing Back,157,Bayer Leverkusen,904,[28381ba1-fca9-492c-a11d-e562c0a79893],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borussia Mönchengladbach,185,00:30:00.402,Foul Committed,NaN
3492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Yellow Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86cb40ff-fc1c-4ebc-b48d-ed1b672afb9d,3372,NaN,"[77.2, 72.2]",3890550,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,Regular Play,Tin Jedvaj,6309.0,Right Back,179,Borussia Mönchengladbach,185,[28d59b39-62ca-4922-9f18-3502bd9a4da2],34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:42:34.282,Foul Committed,NaN

In [11]:
is_yellow = events["foul_committed_card"] == "Yellow Card"
events["yellow_cumul"] = is_yellow.cumsum().shift(1, fill_value=0)

We need to split yellows to home and away team though

In [12]:
home_away = matches[matches["match_id"] == 3890550][
    ["home_team_id", "home_team", "away_team_id", "away_team"]
]
home_away

   home_team_id                 home_team  away_team_id         away_team
1           185  Borussia Mönchengladbach           904  Bayer Leverkusen

In [13]:
events[["home_team", "away_team"]] = home_away[["home_team", "away_team"]].iloc[0]

/var/folders/tv/l4j50kv10gzcv4kzmhysn_fr0000gn/T/ipykernel_77279/2551237640.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  events[["home_team", "away_team"]] = home_away[["home_team", "away_team"]].iloc[0]
/var/folders/tv/l4j50kv10gzcv4kzmhysn_fr0000gn/T/ipykernel_77279/2551237640.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  events[["home_team", "away_team"]] = home_away[["home_team", "away_team"]].iloc[0]

In [14]:
home_away[["home_team", "away_team"]].iloc[0]

home_team    Borussia Mönchengladbach
away_team            Bayer Leverkusen
Name: 1, dtype: object

In [15]:
np.where((events["foul_committed_card"] == "Yellow Card") & (events['possession_team'] == events['home_team']), 1, 0)

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
events[events["foul_committed_card"] == "Yellow Card"][['player', 'possession_team', 'team']]

               player           possession_team                      team
3476      Lars Bender  Borussia Mönchengladbach          Bayer Leverkusen
3484      Oscar Wendt  Borussia Mönchengladbach  Borussia Mönchengladbach
3489  Ibrahima Traoré          Bayer Leverkusen  Borussia Mönchengladbach
3492       Tin Jedvaj  Borussia Mönchengladbach          Bayer Leverkusen

In [ ]:
events['is_home'] = (events['home_team'] == events['team'])
events["is_yellow"] = (events["foul_committed_card"] == "Yellow Card") | (events.get("bad_behaviour_card") == "Yellow Card")
events['home_yellows'] = (events['is_home'] & events['is_yellow'])
events["away_yellows"] = ~events["is_home"] & events["is_yellow"]
events['home_yc_cumul'] = events['home_yellows'].cumsum().shift(1, fill_value=0)
events["away_yc_cumul"] = events["away_yellows"].cumsum().shift(1, fill_value=0)
events[events["is_yellow"]]

In [ ]:
events["is_red"] = (
    (events["foul_committed_card"] == "Red Card")
    | (events["foul_committed_card"] == "Second Yellow")
    | (events.get("bad_behaviour_card") == "Red Card")
    | (events.get("bad_behaviour_card") == "Second Yellow")
)
events["home_reds"] = events["is_home"] & events["is_red"]
events["away_reds"] = ~events["is_home"] & events["is_red"]
events["home_rc_cumul"] = events["home_reds"].cumsum().shift(1, fill_value=0)
events["away_rc_cumul"] = events["away_reds"].cumsum().shift(1, fill_value=0)

events = events.copy()

In [19]:
events['shot_outcome'].unique()

array([nan, 'Post', 'Wayward', 'Off T', 'Saved to Post', 'Saved', 'Goal',
       'Blocked'], dtype=object)

In [20]:
events["is_goal"] = (events["shot_outcome"] == "Goal") | (events["type"] == "Own Goal For")
events["home_goals"] = events["is_home"] & events["is_goal"]
events["away_goals"] = ~events["is_home"] & events["is_goal"]
events["hgoals_cumul"] = events["home_goals"].cumsum().shift(1, fill_value=0)
events["agoals_cumul"] = events["away_goals"].cumsum().shift(1, fill_value=0)
events.tail()

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_no_touch,dribble_nutmeg,dribble_outcome,dribble_overrun,duel_outcome,duel_type,duration,foul_committed_advantage,foul_committed_card,foul_committed_offensive,foul_committed_type,foul_won_advantage,foul_won_defensive,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_outcome,goalkeeper_position,goalkeeper_shot_saved_to_post,goalkeeper_technique,goalkeeper_type,id,index,interception_outcome,location,match_id,minute,off_camera,out,pass_aerial_won,pass_angle,pass_assisted_shot_id,pass_body_part,pass_cross,pass_cut_back,pass_deflected,pass_end_location,pass_goal_assist,pass_height,pass_inswinging,pass_length,pass_outcome,pass_outswinging,pass_recipient,pass_recipient_id,pass_shot_assist,pass_switch,pass_technique,pass_through_ball,pass_type,period,play_pattern,player,player_id,position,possession,possession_team,possession_team_id,related_events,second,shot_aerial_won,shot_body_part,shot_deflected,shot_end_location,shot_first_time,shot_freeze_frame,shot_key_pass_id,shot_one_on_one,shot_outcome,shot_saved_to_post,shot_statsbomb_xg,shot_technique,shot_type,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure,yellow_cumul,home_team,away_team,is_home,is_yellow,home_yellows,away_yellows,home_yc_cumul,away_yc_cumul,is_red,home_reds,away_reds,home_rc_cumul,away_rc_cumul,is_goal,home_goals,away_goals,hgoals_cumul,agoals_cumul
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.63316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5325f10c-6dda-479e-99e9-a87adece976c,3540,NaN,"[98.1, 65.5]",3890550,91,NaN,NaN,NaN,1.026245,NaN,Right Foot,NaN,NaN,NaN,"[102.4, 72.6]",NaN,Ground Pass,NaN,8.300602,Pass Offside,NaN,Robbie Kruse,5494.0,NaN,NaN,NaN,NaN,Recovery,2,From Throw In,Admir Mehmedi,8219.0,Left Midfield,185,Bayer Leverkusen,904,[2defdd0e-3778-4544-afae-a97de67f8d9c],33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:46:33.371,Pass,NaN,4,Borussia Mönchengladbach,Bayer Leverkusen,False,False,False,False,2,2,False,False,False,0,0,False,False,False,2,1
1938,NaN,Incomplete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2defdd0e-3778-4544-afae-a97de67f8d9c,3541,NaN,"[102.4, 72.6]",3890550,91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Throw In,Robbie Kruse,5494.0,Right Midfield,185,Bayer Leverkusen,904,[5325f10c-6dda-479e-99e9-a87adece976c],35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:46:35.004,Ball Receipt*,NaN,4,Borussia Mönchengladbach,Bayer Leverkusen,False,False,False,False,2,2,False,False,False,0,0,False,False,False,2,1
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.25520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06edd28d-9195-4de5-8815-235e76c777d8,3542,NaN,"[17.7, 7.5]",3890550,92,NaN,NaN,NaN,0.396709,NaN,Left Foot,NaN,NaN,NaN,"[69.5, 29.2]",NaN,High Pass,NaN,56.161640,Unknown,NaN,André Hahn,8322.0,NaN,NaN,NaN,NaN,Free Kick,2,From Free Kick,Yann Sommer,5550.0,Goalkeeper,186,Borussia Mönchengladbach,185,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borussia Mönchengladbach,185,00:47:00.965,Pass,NaN,4,Borussia Mönchengladbach,Bayer Leverkusen,True,False,False,False,2,2,False,False,False,0,0,False,False,False,2,1
3528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7ace1fb7-361c-4b8e-b055-2af7b9b47f36,3543,NaN,NaN,3890550,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Free Kick,NaN,NaN,NaN,186,Borussia Mönchengladbach,185,[9c41fa10-13d7-40b9-a5f3-08c48097120e],4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:47:04.162,Half End,NaN,4,Borussia Mönchengladbach,Bayer Leverkusen,False,False,False,False,2,2,False,False,False,0,0,False,False,False,2,1
3529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9c41fa10-13d7-40b9-a5f3-08c48097120e,3544,NaN,NaN,3890550,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Free Kick,NaN,NaN,NaN,186,Borussia Mönchengladbach,185,[7ace1fb7-361c-4b8e-b055-2af7b9b47f36],4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borussia Mönchengladbach,185,00:47:04.162,Half End,NaN,4,Borussia Mönchengladbach,Bayer Leverkusen,True,False,False,False,2,2,False,False,False,0,0,False,False,False,2,1

In [21]:
events.head()

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_no_touch,dribble_nutmeg,dribble_outcome,dribble_overrun,duel_outcome,duel_type,duration,foul_committed_advantage,foul_committed_card,foul_committed_offensive,foul_committed_type,foul_won_advantage,foul_won_defensive,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_outcome,goalkeeper_position,goalkeeper_shot_saved_to_post,goalkeeper_technique,goalkeeper_type,id,index,interception_outcome,location,match_id,minute,off_camera,out,pass_aerial_won,pass_angle,pass_assisted_shot_id,pass_body_part,pass_cross,pass_cut_back,pass_deflected,pass_end_location,pass_goal_assist,pass_height,pass_inswinging,pass_length,pass_outcome,pass_outswinging,pass_recipient,pass_recipient_id,pass_shot_assist,pass_switch,pass_technique,pass_through_ball,pass_type,period,play_pattern,player,player_id,position,possession,possession_team,possession_team_id,related_events,second,shot_aerial_won,shot_body_part,shot_deflected,shot_end_location,shot_first_time,shot_freeze_frame,shot_key_pass_id,shot_one_on_one,shot_outcome,shot_saved_to_post,shot_statsbomb_xg,shot_technique,shot_type,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure,yellow_cumul,home_team,away_team,is_home,is_yellow,home_yellows,away_yellows,home_yc_cumul,away_yc_cumul,is_red,home_reds,away_reds,home_rc_cumul,away_rc_cumul,is_goal,home_goals,away_goals,hgoals_cumul,agoals_cumul
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,872b1174-31fc-4bd1-b77a-031ad6fc5eef,1,NaN,NaN,3890550,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Borussia Mönchengladbach,185,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'formation': 3412, 'lineup': [{'player': {'id...",Borussia Mönchengladbach,185,00:00:00.000,Starting XI,NaN,0,Borussia Mönchengladbach,Bayer Leverkusen,True,False,False,False,0,0,False,False,False,0,0,False,False,False,0,0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b4679dd8-c2e4-49e2-b1ba-4132255c72d9,2,NaN,NaN,3890550,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Borussia Mönchengladbach,185,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'formation': 442, 'lineup': [{'player': {'id'...",Bayer Leverkusen,904,00:00:00.000,Starting XI,NaN,0,Borussia Mönchengladbach,Bayer Leverkusen,False,False,False,False,0,0,False,False,False,0,0,False,False,False,0,0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b7634bbf-f73d-4114-81ab-710f6a423273,3,NaN,NaN,3890550,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Borussia Mönchengladbach,185,[b8c7457e-6921-4760-9cfd-b5ed5a7687f6],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:00.000,Half Start,NaN,0,Borussia Mönchengladbach,Bayer Leverkusen,False,False,False,False,0,0,False,False,False,0,0,False,False,False,0,0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b8c7457e-6921-4760-9cfd-b5ed5a7687f6,4,NaN,NaN,3890550,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,NaN,NaN,NaN,1,Borussia Mönchengladbach,185,[b7634bbf-f73d-4114-81ab-710f6a423273],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borussia Mönchengladbach,185,00:00:00.000,Half Start,NaN,0,Borussia Mönchengladbach,Bayer Leverkusen,True,False,False,False,0,0,False,False,False,0,0,False,False,False,0,0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.45559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53aade16-5698-47e7-8e14-ac97a84a8f8c,5,NaN,"[60.0, 40.0]",3890550,0,NaN,NaN,NaN,0.361729,NaN,Right Foot,NaN,NaN,NaN,"[63.7, 41.4]",NaN,Ground Pass,NaN,3.956008,NaN,NaN,Lars Edi Stindl,8806.0,NaN,NaN,NaN,NaN,Kick Off,1,From Kick Off,Raffael Caetano de Araújo,8810.0,Left Center Forward,2,Borussia Mönchengladbach,185,[e13888d8-cc59-4927-96b6-6807026a4de9],0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Borussia Mönchengladbach,185,00:00:00.459,Pass,NaN,0,Borussia Mönchengladbach,Bayer Leverkusen,True,False,False,False,0,0,False,False,False,0,0,False,False,False,0,0

In [22]:
ml_cols = ['index', 'period', 'minute', 'second', 'is_home', 'hgoals_cumul', 'agoals_cumul', 'away_rc_cumul', 'home_rc_cumul', 'home_yc_cumul', 'away_yc_cumul']

In [23]:
events[['minute', 'second']].head(20)

      minute  second
0          0       0
1          0       0
2          0       0
3          0       0
6          0       0
997        0       0
7          0       0
998        0       2
1939       0       2
8          0       3
999        0       6
2671       0       6
2755       0       6
9          0      11
1000       0      12
1940       0      12
2783       0      12
10         0      12
1001       0      13
11         0      13

In [24]:
events[ml_cols].head()

,index,period,minute,second,is_home,hgoals_cumul,agoals_cumul,away_rc_cumul,home_rc_cumul,home_yc_cumul,away_yc_cumul
0,1,1,0,0,True,0,0,0,0,0,0
1,2,1,0,0,False,0,0,0,0,0,0
2,3,1,0,0,False,0,0,0,0,0,0
3,4,1,0,0,True,0,0,0,0,0,0
6,5,1,0,0,True,0,0,0,0,0,0

In [30]:
ml_cols = [
    "index",
    'id',
    "period",
    "minute",
    "second",
    "is_home",
    "hgoals_cumul",
    "agoals_cumul",
    "away_rc_cumul",
    "home_rc_cumul",
    "home_yc_cumul",
    "away_yc_cumul",
    'duration',
]

events[ml_cols].head()

,index,id,period,minute,second,is_home,hgoals_cumul,agoals_cumul,away_rc_cumul,home_rc_cumul,home_yc_cumul,away_yc_cumul,duration
0,1,872b1174-31fc-4bd1-b77a-031ad6fc5eef,1,0,0,True,0,0,0,0,0,0,0.00000
1,2,b4679dd8-c2e4-49e2-b1ba-4132255c72d9,1,0,0,False,0,0,0,0,0,0,0.00000
2,3,b7634bbf-f73d-4114-81ab-710f6a423273,1,0,0,False,0,0,0,0,0,0,0.00000
3,4,b8c7457e-6921-4760-9cfd-b5ed5a7687f6,1,0,0,True,0,0,0,0,0,0,0.00000
6,5,53aade16-5698-47e7-8e14-ac97a84a8f8c,1,0,0,True,0,0,0,0,0,0,0.45559